[package]
name = "coin"
version = "0.0.1"

[dependencies]
AptosFramework = {git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "devnet"}

[addresses]
coin = "0x815401357d501dc73b084399f692f942eec25a2fc9f2795cb073a3df6330626f"
